# Generated by Django 4.1.2 on 2022-12-07 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.CharField(max_length=4, verbose_name="Seria")),
                ("number", models.CharField(max_length=16, verbose_name="Number")),
                (
                    "release_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Release date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        choices=[
                            (datetime.datetime(1, 12, 7, 23, 39, 38, 447382), "Year"),
                            (
                                datetime.datetime(2023, 6, 7, 23, 39, 38, 447382),
                                "6 months",
                            ),
                            (
                                datetime.datetime(2022, 1, 7, 23, 39, 38, 447382),
                                "1 month",
                            ),
                        ],
                        verbose_name="End date",
                    ),
                ),
                (
                    "used_date",
                    models.DateTimeField(auto_now=True, verbose_name="Used date"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=5.2,
                        verbose_name="Balace",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVATE", "Активирована"),
                            ("NOT_ACTIVATE", "Не активирована"),
                            ("OVERDUE", "Просрочена"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authapp.abstractusermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoryCardModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_purshace",
                    models.CharField(max_length=50, verbose_name="Place of purshace"),
                ),
                (
                    "purshace_amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=5.2, verbose_name="Purshace ampunt"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.cardsmodel"
                    ),
                ),
            ],
        ),
    ]
