# Generated by Django 4.1.2 on 2022-12-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardsmodel",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Balace"
            ),
        ),
        migrations.AlterField(
            model_name="cardsmodel",
            name="end_date",
            field=models.DateTimeField(verbose_name="End date"),
        ),
    ]
